### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DmitriySimonov** [gabrimatic/restart_app#11]
```
17:19:10.130  E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel restart)
                 #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
                 <asynchronous suspension>
                 #1      Restart.restartApp (package:restart_app/restart_app.dart:26:8)
                 <asynchronous suspension>
```
                 
                 
lutter doctor
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libscela${PLATFORM}.so.6' from /etc/ld.so.preload cannot be preloaded (failed to map segment from shared object): ignored.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Ubuntu 22.04.2 LTS 5.15.0-72-generic, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by gabrimatic** [comment]
Dear Dmitriy,

Thank you for bringing this to our attention. Based on the error message
you've posted, it seems like there might be some confusion around the
platform you're trying to run the restart_app package on.

If you're trying to use this package on a Linux platform, please be aware
that as of the current version,* the restart_app package does not support
Linux*. It is currently designed to work with Flutter applications on iOS,
Android, and web platforms. Unfortunately, trying to use this package on
unsupported platforms might result in errors like the one you've
encountered.

If you're using an iOS, Android, or web platform, which are supported by
the restart_app package, and you're still encountering this issue, you
might be dealing with a *build problem*. In this case, clearing your build
and package cache could help.
You can do this by running the following commands in your terminal:

flutter clean
> flutter pub get
> flutter run


I hope this helps resolve your issue. If you're still encountering problems
after following these steps, please feel free to provide more information
or ask additional questions.

Kind regards
Hossein
